accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("password/", views.password, name="password"),
    path("delete/", views.delete, name="delete"),
    path("mypage/<int:pk>/", views.mypage, name="mypage"),
    path("profile/<int:pk>/", views.profile, name="profile"),
    path("pupdate/", views.pupdate, name="pupdate"),
    path("follow/<int:pk>/", views.follow, name="follow"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("index/", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/detail", views.detail, name="detail"),
    path("<int:pk>/update", views.update, name="update"),
    path("<int:pk>/delete", views.delete, name="delete"),
    path("<int:category_pk>/category/", views.category, name="category"),
    path("<int:category_pk>/follow/", views.category_follow, name="category_follow"),
    path("<int:pk>/like/", views.like, name="like"),
    path("comment/<int:pk>", views.comment, name="comment"),
    path("commend_d", views.comment_d, name="comment_d"),
    path("search/", views.search, name="search"),
]

softCream/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail


class User(AbstractUser):
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )
    pass


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="profile"
    )
    image = models.ImageField(
        upload_to="images/",
        blank=True,
    )
    thumbnail = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[Thumbnail(300, 400)],
        format="JPEG",
    )
    status = models.CharField(max_length=100, blank=True)

articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)
    category_followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='category_followings')
    def __str__(self):
      return self.name

class Articles(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)    
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_articles')

class Comment(models.Model):
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    articles = models.ForeignKey(Articles, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Photo(models.Model):
    post = models.ForeignKey(Articles, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

class Image(models.Model):
    articles = models.ForeignKey(Articles, on_delete=models.CASCADE, related_name='articles_image')
    image = ProcessedImageField(upload_to='images/', blank=True,
                                processors=[ResizeToFill(1200, 960)],
                                format='JPEG',
                                options={'quality': 80})
    image_thumbnail = ImageSpecField(source='image',
                                processors=[ResizeToFill(200, 200)],
                                format='JPEG',
                                options={'quality': 60})

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from django import forms
from .models import Profile


class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = (
            "username",
            "password1",
            "password2",
            "last_name",
            "email",
        )
        labels = {
            "username": "아이디",
            "password1": "비밀번호",
            "password2": "비밀번호 확인",
            "last_name": "이름",
            "email": "이메일",
        }


class UpdateForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            "email",
            "first_name",
            "last_name",
        )
        labels = {
            "email": "이메일",
            "first_name": "성",
            "last_name": "이름",
        }


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            "image",
            "status",
        ]
        labels = {"image": "프로필 이미지", "status": "상태 메세지"}

accounts/views.py
from ast import Pass

from django.http import JsonResponse
from .models import Profile, User
from articles.models import Articles
from django.shortcuts import render, redirect

from accounts.forms import SignupForm, UpdateForm, ProfileForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    users = User.objects.all()
    context = {
        "users": users,
    }
    return render(request, "accounts/index.html", context)


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        profile = Profile()
        if form.is_valid():
            user = form.save()
            profile.user = user
            profile.save()
            return redirect("articles:index")
    else:
        form = SignupForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "articles:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("articles:index")


@login_required
def update(request):
    if request.method == "POST":
        form = UpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("articles:index")
    else:
        form = UpdateForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


@login_required
def password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("accounts:update")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/password.html", context)


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("articles:index")


def mypage(request, pk):
    user = get_user_model().objects.get(pk=pk)
    articles = Articles.objects.filter(user=user)
    context = {
        "user": user,
        "articles": articles,
    }
    return render(request, "accounts/mypage.html", context)


def profile(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        "user": user,
    }
    return render(request, "accounts/profile.html", context)


@login_required
def pupdate(request):
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect("accounts:profile", request.user.pk)
    else:
        form = ProfileForm(instance=request.user.profile)
    context = {
        "form": form,
    }
    return render(request, "accounts/pupdate.html", context)


@login_required
def follow(request, pk):
    if request.user.is_authenticated:
        me = request.user
        user = get_user_model().objects.get(pk=pk)
        if me != user:
            if me in user.followers.all():
                user.followers.remove(me)
                is_followed = False
            else:
                user.followers.add(me)
                is_followed = True
            context = {
                "is_followed": is_followed,
                "followersC": user.followers.count(),
                "followingsC": user.followings.count(),
            }
            return JsonResponse(context)
        return redirect("accounts:mypage", pk)
    return redirect("accounts:login")

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}
<div class="container">
    <h1 class='text-center my-5'>Accounts Index 페이지</h1>
    <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">UserID</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
            <colgroup>
                <col style='width:5%'>
                <col style='width:20%'>
                <col style='width:10%'>
                <col style='width:15%'>
                <col style='width:50%'>
            </colgroup>
        {% for user in users %}
        <tr onclick='location.href="{% url 'accounts:mypage' user.pk %}"' style='cursor: pointer;'>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
                {% if user.profile.image %}
                <img src="{{ user.profile.image.url }}" alt="{{ user.profile.image }}" style='width:2rem; height:2.2rem' class='rounded-circle me-3'>{{ user.username }}
                {% else %}
                <img src="{% static 'profile/guest.png' %}" alt="guest-img" style='width:2rem' class='rounded-circle me-3'>{{ user.username }}
                {% endif %}
            </td>
            <td><p class='mb-0 mt-1'>{{ user.last_name }}{{ user.first_name }}</p></td>
            <td><p class='mb-0 mt-1'>{{ user.email }}</p></td>
            <td><p class='mb-0 mt-1'>{{ user.profile.status }}</p></td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
</div>
{% endblock  %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="d-flex justify-content-center">
    <div style='width:30rem;margin: 3rem 0 0 0'>
        <h1 class='text-center fw-bold'>Soft Cream</h1>
        <form action="" method='POST'>
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="d-grid" style='margin: 2rem 0 0 0'>
                <input type="submit" value="로그인" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>

{% endblock  %}

accounts/templates/accounts/mypage.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}
<div class="container">
    <div class="d-flex justify-content-center flex-column">
        <h1 class='text-center fw-bold my-5'>마이 페이지</h1>
        <div class='d-flex'>
            <div class='me-3' onclick='location.href="{% url 'accounts:profile' user.pk %}"' style='cursor: pointer;'>
                {% if user.profile.image %}
                <img src="{{ user.profile.image.url }}" alt="" style='width:5rem; height:5rem' class='rounded-circle'>
                {% elif user.profile.thumbnail.image %}
                <img src="{{ user.profile.thumbnail.url }}" alt="" style='width:5rem; height:5rem' class='rounded-circle'>
                {% else %}
                <img src="{% static 'profile/guest.png' %}" alt="" style='width:5rem; height:5rem' class='rounded-circle'>
                {% endif %}
            </div>
            <div>
                <div>
                    <a class='btn btn-light mb-2' href='{% url 'accounts:profile' user.pk %}'>{{ user }}</a>
                    {% if request.user.is_authenticated %}
                    {% if request.user != user %}
                        {% if request.user in user.followers.all %}
                        <span id='follow' data-user-id='{{ user.pk }}' class='btn btn-light mb-2'>팔로잉</span>
                        {% else %}
                        <span id='follow' data-user-id='{{ user.pk }}' class='btn btn-dark mb-2'>팔로우</span>
                        {% endif %}
                    {% endif %}
                    {% endif %}
                </div>
                    {% if request.user == user %}
                <div>
                    <a href="{% url 'accounts:update' %}" class="btn btn-warning">정보수정</a>
                </div>
                {% endif %}
            </div>
        </div>
        <div class='d-flex my-4'>
            <p class="small fw-bold me-4">전체 게시글 </p> 
            <p class="small fw-bold me-4 text-primary">팔로워 <span id='followers' class='text-dark'>{{ user.followers.count }}</span></p>
            <p class="small fw-bold text-primary">팔로잉 <span id='followings' class='text-dark'>{{ user.followings.count }}</span></p>
        </div>
        {% if user.category_followings.all %}

        {% comment %} 나이키 1 아디다스 2 뉴발란스 3 etc 4 {% endcomment %}

        <p class='fw-bold'>팔로우한 브랜드</p>
        <div class='d-flex'>
            {% for c in user.category_followings.all %}
                {% if c.name == 'adidas' %}
                <a href="{% url 'articles:category' c.pk %}" class='mx-2'>
                    <img src="{% static 'images/아디다스인덱스.jpg' %}" class="rounded-pill" style="width:4rem; height:4rem">
                </a>
                {% elif c.name == 'nike' %}
                <a href="{% url 'articles:category' c.pk %}" class='mx-2'>
                    <img src="{% static 'images/나이키인덱스.png' %}" class="rounded-pill" style="width:4rem; height:4rem">
                </a>
                {% elif c.name == 'newbalance' %}
                <a href="{% url 'articles:category' c.pk %}" class='mx-2'>
                    <img src="{% static 'images/뉴발란스_로고_(2).png' %}" class="rounded-pill" style="width:4rem; height:4rem">
                </a>
                {% else %}
                <a href="{% url 'articles:category' c.pk %}" class='mx-2'>
                    <img src="{% static 'images/jordan.png' %}" class="rounded-pill" style="width:4rem; height:4rem">
                </a>
                {% endif %}
            {% endfor %}
        </div>

        <h3 class='fw-bold my-5'>관심 목록</h3>

        <div class='container'>
            <div class='row'>
            {% for article in user.like_articles.all %}
                <div class='col-6 col-sm-3'>
                    {% if article.articles_image.all|length %}
                        {% for image in article.articles_image.all %}
                        {% if forloop.counter == 1 %}
                        <a href="{% url 'articles:detail' article.pk %}"><img src="{{ image.image.url }}" alt="{{ image.image }}" class="rounded-4" style='width:100%;'></a>
                        {% endif %}
                        {% endfor %}
                    {% else %}
                    <a href="{% url 'articles:detail' article.pk %}"><img src="{% static 'images/6c757d.jpg' %}" alt="" class="rounded-4" style='width:100%;'></a>
                    {% endif %}
                    <div class='justify-content-center'>
                        <a href="{% url 'accounts:mypage' article.user.pk %}" class='text-decoration-none'>
                            {% if article.user.profile.image %}
                            <img src="{{ article.user.profile.image.url }}" style='width:3rem;height:3rem' class='rounded-circle my-1' alt="">
                            {% else %}
                            <img src="{% static 'profile/guest.jpg' %}" style='width:3rem;height:3rem' class='rounded-circle my-1' alt="">
                            {% endif %}
                        </a>
                        <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill mx-2" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                        </svg>{{ article.like_users.count }}</span>
                        <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat mx-2" viewBox="0 0 16 16">
                            <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
                        </svg>{{ article.comment_set.count }}</span>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>

        

        {% endif %}

        <h3 class='fw-bold my-5'>작성한 글</h3>

        <div class='container'>
            <div class='row'>
            {% for article in articles %}
                <div class='col-6 col-sm-3'>
                    {% if article.articles_image.all|length %}
                        {% for image in article.articles_image.all %}
                        {% if forloop.counter == 1 %}
                        <a href="{% url 'articles:detail' article.pk %}"><img src="{{ image.image.url }}" alt="{{ image.image }}" class="rounded-4" style='width:100%;'></a>
                        {% endif %}
                        {% endfor %}
                    {% else %}
                    <a href="{% url 'articles:detail' article.pk %}"><img src="{% static 'images/6c757d.jpg' %}" alt="" class="rounded-4" style='width:100%;'></a>
                    {% endif %}
                    <div class='justify-content-center'>
                        <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill mx-2" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                        </svg>{{ article.like_users.count }}</span>
                        <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat mx-2" viewBox="0 0 16 16">
                            <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
                        </svg>{{ article.comment_set.count }}</span>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>


        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    const followBtn = document.querySelector('#follow')
    followBtn.addEventListener('click', function(event) {
        axios({
            method: 'get',
            url: `/accounts/follow/${event.target.dataset.userId}/`
        })
        .then(response => {
            if( response.data.is_followed == true) {
                event.target.classList.remove('btn-dark')
                event.target.classList.add('btn-light')
                followBtn.innerText= '팔로잉'
            } else {
                event.target.classList.remove('btn-light')
                event.target.classList.add('btn-dark')
                followBtn.innerText='팔로우'
            }
            const followers = document.querySelector('#followers')
            const followings = document.querySelector('#followings')
            followers.innerText = response.data.followersC
            followings.innerText = response.data.followingsC
        })
    })
</script>
    {% endblock  %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container">
    <div class="d-flex justify-content-center">
        <div style='width:30rem'>
            <h1 class="text-center fw-bold">Soft Cream</h1>
            <form action="{% url 'accounts:password' %}" method='POST'>
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="d-grid">
                    <input type="submit" value="비밀번호 변경" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>

</div>
{% endblock  %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}
<div class="container">
    <h1 class="fw-bold my-5 border border-dark border-top-0 border-start-0 border-end-0 border-5 pb-3">프로필 정보</h1>
    <div class="row">
        <div class="col-12 col-md-6 d-flex flex-column align-content-center mb-5" >
            <div class='row '>
                
                {% if user.profile.image %}
                <div class='col-5 '>
                    <img src="{{ user.profile.image.url }}" alt="{{ user.profile.image }}">
                    {% if request.user == user %}
                    <div class='text-center d-grid'>
                        <a href="{% url 'accounts:pupdate' %}" class='btn btn-primary my-2'>프로필 업데이트</a>
                    </div>
                    {% endif %}
                </div>

                {% elif user.profile.thumbnail %}
                    
                <div class='col-5 '>
                    <img src="{{ user.profile.thumbnail.url }}" alt="{{ user.profile.thumbnail }}" >
                    {% if request.user == user %}
                    <div class='text-center d-grid'>
                        <a href="{% url 'accounts:pupdate' %}" class='btn btn-primary my-2'>프로필 업데이트</a>
                    </div>
                    {% endif %}
                </div>

                {% else %}
                <div class='row '>
                    <img src="{% static 'profile/guest.png' %}" alt="" class='text-cneter' style='width:20rem'>
                    {% if request.user == user %}
                    <div class='text-center d-grid' style='width:20rem'>
                        <a href="{% url 'accounts:pupdate' %}" class='btn btn-primary my-2'>프로필 업데이트</a>
                    </div>
                    {% endif %}
                </div>

                {% endif %}
            </div>
        </div>
        <div class="col-12 col-md-6">
            <p class='fw-bold'>아이디 : <span class='fw-light'> {{ user }} </span></p>
            <p class='fw-bold'>이메일 : <span class='fw-light'> {{ user.email }} </span></p>
            <p class='fw-bold'>이름 : <span class='fw-light'> {{ user.first_name }} {{ user.last_name }} </span> </p>
            <p class='fw-bold'>상태메세지 : <span class='fw-light'> {{ user.profile.status }} </span></p>
        </div>
    </div>
</div>
{% endblock  %}

accounts/templates/accounts/pupdate.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container">
    <div class="d-flex justify-content-center">
        <div style='width:30rem'>
            <h1 class="text-center fw-bold my-5">프로필 수정</h1>
            <form action="{% url 'accounts:pupdate' %}" method='POST' enctype='multipart/form-data'>
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="d-grid my-4">
                    <input type="submit" value="회원정보수정" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock  %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container">
    <div class="d-flex justify-content-center">
        <div style='width:30rem;margin: 3rem 0 0 0'>
            <h1 class="text-center fw-bold">Soft Cream</h1>
            <form action="{% url 'accounts:signup' %}" method='POST'>
                {% csrf_token %}
                {% for field in form %}
                <div>
                    {% bootstrap_field field %}
                    <div class='d-none'>
                        {{ field.label }}
                    </div>
                </div>
                {% endfor %}
                <div class="d-grid">
                    <input type="submit" value="회원가입" class="btn btn-primary">
                </div>
            </form>
        </div>
    </div>

</div>
{% endblock  %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container">
    <div class="d-flex justify-content-center">
        <div style='width:30rem'>
            <h1 class="text-center fw-bold">Soft Cream</h1>
            <form action="{% url 'accounts:update' %}" method='POST'>
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="d-grid gap-2">
                    <input type="submit" value="수정하기" class="btn btn-primary">
                    <a href="{% url 'accounts:password' %}" class="btn btn-warning">비밀번호변경</a>
                    <a href="{% url 'accounts:delete' %}" class="btn btn-danger">계정 삭제</a>
                </div>
            </form>
        </div>
    </div>

</div>
{% endblock  %}