accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("password/", views.password, name="password"),
    path("delete/", views.delete, name="delete"),
    path("mypage/<int:pk>/", views.mypage, name="mypage"),
    path("profile/<int:pk>/", views.profile, name="profile"),
    path("pupdate/", views.pupdate, name="pupdate"),
    path("follow/<int:pk>/", views.follow, name="follow"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("index/", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/detail", views.detail, name="detail"),
    path("<int:pk>/update", views.update, name="update"),
    path("<int:pk>/delete", views.delete, name="delete"),
    path("<int:category_pk>/category/", views.category, name="category"),
    path("<int:category_pk>/follow/", views.category_follow, name="category_follow"),
    path("<int:pk>/like/", views.like, name="like"),
    path("comment/<int:pk>", views.comment, name="comment"),
    path("commend_d", views.comment_d, name="comment_d"),
    path("search/", views.search, name="search"),
]

softCream/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)
    category_followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='category_followings')
    def __str__(self):
      return self.name

class Articles(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)    
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_articles')

class Comment(models.Model):
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    articles = models.ForeignKey(Articles, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Photo(models.Model):
    post = models.ForeignKey(Articles, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

class Image(models.Model):
    articles = models.ForeignKey(Articles, on_delete=models.CASCADE, related_name='articles_image')
    image = ProcessedImageField(upload_to='images/', blank=True,
                                processors=[ResizeToFill(1200, 960)],
                                format='JPEG',
                                options={'quality': 80})
    image_thumbnail = ImageSpecField(source='image',
                                processors=[ResizeToFill(200, 200)],
                                format='JPEG',
                                options={'quality': 60})

articles/forms.py
from django import forms
from .models import Articles, Comment, Category, Image


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Articles
        fields = ("title", "content", "category")
        labels = {
            "title": "제목",
            "content": "내용",
            "category": "카테고리",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]
        labels = {
            "content": " ",
        }

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

        self.fields["content"].widget.attrs = {
            "class": "form-control me-3",
            "placeholder": "댓글을 입력해주세요",
            "rows": 1,
        }


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = [
            "image",
        ]

articles/views.py
from django.shortcuts import render, redirect
from .models import Articles
from .models import Articles, Category, Comment, Image
from .forms import ArticleForm, CommentForm, ImageForm
from django.views.decorators.http import require_http_methods
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.db import transaction
from django.db.models import Count
import datetime
import json

from django.db.models import Q


# Create your views here.
def index(request):
    articles = Articles.objects.order_by("-pk")
    new_articles = Articles.objects.filter(
        created_at__gte=datetime.datetime.now() - datetime.timedelta(hours=24)
    ).order_by("-pk")[:6]
    lookbook_articles = Articles.objects.annotate(
        like_count=Count("like_users")
    ).order_by("-like_count", "-pk")
    image = Image.objects.order_by("-pk")
    form = CommentForm()
    context = {
        "articles": articles,
        "new_articles": new_articles,
        "lookbook_articles": lookbook_articles,
        "image": image,
        "form": form,
    }
    return render(request, "articles/index.html", context)


@login_required
def create(request):
    if request.method == "POST":
        article_forms = ArticleForm(request.POST, request.FILES)
        image_form = ImageForm(request.POST, request.FILES)
        images = request.FILES.getlist("image")
        if article_forms.is_valid() and image_form.is_valid():
            article_form = article_forms.save(commit=False)
            article_form.user = request.user
            if len(images):
                for image in images:
                    image_instance = Image(articles=article_form, image=image)
                    article_form.save()
                    image_instance.save()
            else:
                article_form.save()
            return redirect("articles:index")
    else:
        article_form = ArticleForm()
        image_form = ImageForm()
    context = {
        "article_form": article_form,
        "image_form": image_form,
    }
    return render(request, "articles/create.html", context)


def detail(request, pk):
    article = Articles.objects.get(pk=pk)
    form = CommentForm()
    context = {
        "article": article,
        "form": form,
    }
    return render(request, "articles/detail.html", context)


@require_http_methods(["GET", "POST"])
def update(request, pk):
    article = Articles.objects.get(pk=pk)
    # image = Image.objects.get(pk=pk)
    if request.method == "POST":
        article_forms = ArticleForm(request.POST, request.FILES, instance=article)
        image_form = ImageForm(request.POST, request.FILES, instance=article)
        images = request.FILES.getlist("image")
        if article_forms.is_valid() and image_form.is_valid():
            article = article_forms.save(commit=False)
            # image_form = article_forms.save(commit=False)
            if len(images):
                for image in images:
                    image_instance = Image(articles=article, image=image)
                    article.save()
                    image_instance.save()
            else:
                article_form.save()
            return redirect("articles:detail", article.pk)
    else:
        article_form = ArticleForm(instance=article)
        image_form = ImageForm(instance=article)
    context = {
        "article_form": article_form,
        "image_form": image_form,
    }
    return render(request, "articles/update.html", context)


def delete(request, pk):
    article = Articles.objects.get(pk=pk)
    article.delete()
    return redirect("articles:index")


def category(request, category_pk):
    category = Category.objects.get(pk=category_pk)
    category_articles = (
        Articles.objects.filter(category=category)
        .annotate(like_count=Count("like_users"))
        .order_by("-like_count", "-pk")
    )
    context = {"category": category, "category_articles": category_articles}
    return render(request, "articles/category.html", context)


@login_required
def category_follow(request, category_pk):
    category = Category.objects.get(pk=category_pk)
    if request.user in category.category_followers.all():
        category.category_followers.remove(request.user)
        category_follow = False
    else:
        category.category_followers.add(request.user)
        category_follow = True
    return JsonResponse(
        {
            "categoryFollow": category_follow,
            "followCount": category.category_followers.count(),
        }
    )


@login_required
def like(request, pk):
    article = Articles.objects.get(pk=pk)
    if request.user in article.like_users.all():
        article.like_users.remove(request.user)
        is_liked = False
    else:
        article.like_users.add(request.user)
        is_liked = True
    return JsonResponse({"isLiked": is_liked, "likeCount": article.like_users.count()})


def comment(request, pk):
    article = Articles.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.articles = article
        comment.user = request.user
        comment.save()
        context = {
            "content": comment.content,
            "userName": comment.user.username,
            "userImgUrl": comment.user.profile.image.url,
            "created": comment.create_at,
            "comment_count": article.comment_set.count(),
            "user": comment.user.pk,
        }
        return JsonResponse(context)
    return redirect("articles:detail", article.pk)


def comment_d(request):
    jsonObject = json.loads(request.body)
    context = {"result": "no"}
    reply = Comment.objects.filter(id=jsonObject.get("replyId"))

    if reply is not None:
        reply.delete()
        context = {
            "result": "ok",
        }
        return JsonResponse(context)
    return JsonResponse(context)


def search(request):
    searched = request.GET.get("searched", False)
    field = request.GET.get("field")
    if field == "1":
        articles = Articles.objects.filter(
            Q(title__contains=searched)
            | Q(content__contains=searched)
            | Q(user__username__contains=searched)
        ).order_by("-pk")
    elif field == "2":
        articles = Articles.objects.filter(Q(title__contains=searched)).order_by("-pk")
    elif field == "3":
        articles = Articles.objects.filter(Q(content__contains=searched)).order_by(
            "-pk"
        )
    elif field == "4":
        articles = Articles.objects.filter(
            Q(user__username__contains=searched)
        ).order_by("-pk")
    if not searched:
        articles = []
        text = "검색어를 입력하세요."
    elif len(articles) == 0:
        text = "검색 결과가 없습니다."
    else:
        text = ""
    context = {
        "articles": articles,
        "text": text,
    }
    return render(request, "articles/search.html", context)

articles/templates/articles/append.html
<div class="d-flex mb-3">
    <div class='me-2' onclick='location.href="{% url 'accounts:mypage' comment.user.pk %}"' style='cursor: pointer;'>
        {% if comment.user.profile.image %}
        <img src="{{ comment.user.profile.image.url }}" alt="{{ comment.user.profile.image }}" style='width:2rem;height:2rem' class='rounded-circle'>
        {% else %}
        <img src="{% static 'profile/guest.png' %}" alt="guest" style='width:2rem;height:2rem' class='rounded-circle'>
        {% endif %}
    </div>
    <div class='d-flex flex-column'>
        <p class='p-0 mb-0 text-start fw-bold small' style='font-size:10px'>{{ comment.user }}</p>
        <p class='p-0 mb-0 small' style='font-size:10px'>{{ comment.create_at }}</p>
    </div>
    <div class='ms-3'>
        <p class='fw-light'>{{ comment.content }}</p>
    </div>
</div>

articles/templates/articles/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class='d-flex justify-content-center'>
    {% if category.id == 1 %}
    <img src="{% static 'images/나이키.png' %}" class='rounded-pill' style="width: 150px; height: 150px;" alt="...">
    {% elif category.id == 2 %}
    <img src="{% static 'images/아디다스.jpg' %}" class='rounded-pill' style="width: 150px; height: 150px;" alt="...">
    {% elif category.id == 3 %}
    <img src="{% static 'images/뉴발란스.jfif' %}" class='rounded-pill' style="width: 150px; height: 150px;" alt="...">
    {% elif category.id == 4 %}
    <img src="{% static 'images/jordan.png' %}" class='rounded-pill' style="width: 150px; height: 150px;" alt="...">
    {% endif %}
</div>
<div class='text-center'>
    <h3 class="text-center p-2">{{ category.name }}</h3>
    {% if request.user.is_authenticated %}
        {% if request.user in category.category_followers.all %}
        <span id='follow' data-category-id='{{ category.pk }}' class='btn btn-outline-primary mb-2'>팔로우 취소</span>
        {% else %}
        <span id='follow' data-category-id='{{ category.pk }}' class='btn btn-primary mb-2'>팔로우</span>
        {% endif %}
    {% endif %}
    <p class="text-center pb-2"><span class="mx-2">게시물 <b>{{ category.category_articles.count }}</b></span><span class="mx-2">팔로워 <b id='followers'>{{ category.category_followers.count }}</b></span></p>
</div>
<div class='container'>
    <div class='row'>
    {% for article in category_articles %}
        <div class='col-6 col-sm-3'>
            {% if article.articles_image.all|length %}
                {% for image in article.articles_image.all %}
                {% if forloop.counter == 1 %}
                <a href="{% url 'articles:detail' article.pk %}"><img src="{{ image.image.url }}" alt="{{ image.image }}" class="rounded-4" style='width:100%;'></a>
                {% endif %}
                {% endfor %}
            {% else %}
            <a href="{% url 'articles:detail' article.pk %}"><img src="{% static 'images/6c757d.jpg' %}" alt="" class="rounded-4" style='width:100%;'></a>
            {% endif %}
            <div class='justify-content-center'>
                <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart-fill mx-2" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                </svg>{{ article.like_users.count }}</span>
                <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat mx-2" viewBox="0 0 16 16">
                    <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
                </svg>{{ article.comment_set.count }}</span>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}
{% block script1 %}
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

    <script>
        const followBtn = document.querySelector('#follow')
        followBtn.addEventListener('click', function(event) {
            console.log(event.target.dataset)
            axios({
                method: 'get',
                url: `/articles/${event.target.dataset.categoryId}/follow/`
            })
            .then(response => {
                if (response.data.categoryFollow === true) {
                    event.target.classList.remove('btn-primary')
                    event.target.classList.add('btn-outline-primary')
                    followBtn.innerText= '팔로우 취소'
                } else {
                    event.target.classList.remove('btn-outline-primary')
                    event.target.classList.add('btn-primary')
                    followBtn.innerText='팔로우'
                }
                const followers = document.querySelector('#followers')
                followers.innerText = response.data.followCount

            })
        })
    </script>
{% endblock script1 %}

articles/templates/articles/create.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}

<div class="container col-12 col-sm-10 col-md-9 col-lg-8">
  <div class="text-center my-5 "><h1 class='fw-bold'>새로운 글</h1></div>
  <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="text-end">
        <input type="submit" value="작성하기" class="btn btn-primary">
      </div>
      {% bootstrap_form article_form %}

      <div class="d-flex justify-content-between">
        <input type="file" name="image" style="cursor:pointer;" multiple >
        <a href="{% url 'articles:index' %}" class="btn btn-dark" >홈으로</a>
      </div>
  </form>
</div>
{% endblock %}

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% load humanize %}
{% block content %}

<div class="modal fade2" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-footer flex-column">
            <div class='d-grid' style='width:470px;'>
                <a href="{% url 'articles:update' article.pk %}" class="btn text-primary" >글 수정</a>
                <hr>
                <a href="{% url 'articles:delete' article.pk %}" class='btn text-danger'>글 삭제</a>
            </div>
        </div>
      </div>
    </div>
  </div>
<main class="container w-50">
    <div class="d-flex justify-content-between my-1 mt-5">
        <div class="d-flex my-3" onclick='location.href="{% url 'accounts:mypage' article.user.pk %}"' style='cursor: pointer;'>
            <div class='me-2'>
                {% if article.user.profile.image %}
                <img src="{{ article.user.profile.image.url }}" alt="{{ article.user.profile.image }}" style='width:3rem;height:3rem' class='rounded-circle'>
                {% else %}
                <img src="{% static 'profile/guest.png' %}" alt="guest" style='width:3rem;height:3rem' class='rounded-circle'>
                {% endif %}
            </div>
            <div class='d-flex flex-column'>
                <p class='p-0 mb-0 text-start fw-bold'>{{ article.user }}</p>
                <p class='p-0 mb-0 fw-light'>{{  article.updated_at|naturaltime }}</p>
            </div>
        </div>
        <div class="d-flex align-content-center">
            {% if request.user.is_authenticated %}
                {% if request.user != article.user %}
                    {% if request.user in article.user.followers.all %}
                    <span id='follow' data-user-id='{{ article.user.pk }}' class='btn btn-light my-4 px-4'>팔로잉</span>
                    {% else %}
                    <span id='follow' data-user-id='{{ article.user.pk }}' class='btn btn-dark my-4 px-4'>팔로우</span>
                    {% endif %}
                {% else %}
                    <button type="button" class="btn my-4" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
                            <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                          </svg>
                    </button>
                {% endif %}
            {% else %}
                <a href="{% url 'accounts:login' %}" class='btn btn-dark my-4 px-4'>팔로우</a>
            {% endif %}
        </div>
    </div>


<!-- Slideshow container -->
<div class="slideshow-container">

    <!-- Full-width images with number and caption text -->
    {% for i in article.articles_image.all %}
    <div class="mySlides">
      <div class="numbertext">{{ forloop.counter }} / {{ article.articles_image.count }}</div>
      <img src="{{ i.image.url }}" style="width:100%">
    </div>
    {% endfor %}
  
    <!-- Next and previous buttons -->
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>
  </div>
  <br>
  
  <!-- The dots/circles -->
  <div style="text-align:center">
{% for i in article.articles_image.all %}
    <span class="dot" onclick="currentSlide({{ forloop.counter }})"></span>
{% endfor %}
  </div>


  <div class="d-flex justify-content-between">
    <div class="d-flex">
        <div class='d-flex justify-content-center my-3 text-danger'>
            {% if request.user.is_authenticated %}
            {% if request.user in article.like_users.all %}
            <i id='like-btn' data-article-id="{{ article.pk }}" class="bi bi-heart-fill"></i>
            {% else %}
            <i id='like-btn' data-article-id="{{ article.pk }}" class="bi bi-heart"></i>
            {% endif %}
            {% endif %}
            <span id="like-count" class='px-2'>
                {{ article.like_users.count }}
            </span>
        </div>
        <div class='my-3'>
            <span onclick="openNav()">
                <i class="bi bi-chat pb-1" style='cursor: pointer;'></i>
            </span>
        </div>
    </div>

    <div class="d-flex align-items-center">
        <a href="javascript:sendLinkFacebook()"><i class="bi bi-facebook me-2"></i></a>
        <a href="javascript:sendLinkTwitter()"><i class="bi bi-twitter"></i></a>
        <script>
                function sendLinkFacebook(){
    var facebook_share_url = "https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}";
    window.open(facebook_share_url,
                'Share on Facebook',
                'scrollbars=no, width=500, height=500');
    } 

    function sendLinkTwitter(){
    var twitter_share_text="{{ post.title }}";
    var twitter_share_url="{{ request.build_absolute_uri }}";
    window.open("https://twitter.com/share?text="+twitter_share_text+"&url="+twitter_share_url,
                'Share on Twitter',
                'scrollbars=no, width=500, height=500');
    }
        </script>
    </div>
</div>

    <p style="font-size: 2rem;" class="my-2">[{{ article.category }}]{{ article.title }} </p>
    <p class="my-2">{{ article.content }} </p>

    <div>
    {% if article.comment_set %}
    {% comment %} <p id='comment_c'>댓글 <span class='fw-bold'>{{ article.comment_set.count }}</span>개</p> {% endcomment %}
    <div id='comment2'>
        {% for comment in article.comment_set.all %}
        <div class='d-flex justify-content-between' id='reply{{ comment.pk }}'>
            <div class="d-flex mb-3">
                <div class='me-2' onclick='location.href="{% url 'accounts:mypage' comment.user.pk %}"' style='cursor: pointer;'>
                    {% if comment.user.profile.image %}
                    <img src="{{ comment.user.profile.image.url }}" alt="{{ comment.user.profile.image }}" style='width:2rem;height:2rem' class='rounded-circle'>
                    {% else %}
                    <img src="{% static 'profile/guest.png' %}" alt="guest" style='width:2rem;height:2rem' class='rounded-circle'>
                    {% endif %}
                </div>
                <div class='d-flex flex-column'>
                    <p class='p-0 mb-0 text-start fw-bold small' style='font-size:10px'>{{ comment.user }}</p>
                    <p class='p-0 mb-0 small' style='font-size:10px'>{{ comment.create_at|naturaltime }}</p>
                </div>
                <div class='ms-3 mt-1'>
                    <p class='fw-light'>{{ comment.content }}</p>
                </div>
            </div>
            {% if request.user == comment.user %}
            <div>
                <span onclick='replyDelete({{ comment.pk }});' class='btn btn-secondary px-1 py-1'>삭제</span>
            </div>
            {% endif %}
        </div>
        {% comment %} {% empty %}
        <p>댓글이 없습니다.</p> {% endcomment %}
        {% endfor %}
    </div>
    {% endif %}
    </div>
</main>
<script>
    let slideIndex = 1;
showSlides(slideIndex);

// Next/previous controls
function plusSlides(n) {
  showSlides(slideIndex += n);
}

// Thumbnail image controls
function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  let i;
  let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
}

{% comment %} 좋아요  {% endcomment %}
</script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    const likeBtn = document.querySelector('#like-btn')
    likeBtn.addEventListener('click', function (event) {
        console.log(event.target.dataset)
        axios({
            method: 'get',
            url: `/articles/${event.target.dataset.articleId}/like/`,
        })
        .then(response => {
            console.log(response)
            console.log(response.data)
            if (response.data.isLiked === true) {
                event.target.classList.add('bi-heart-fill')
                event.target.classList.remove('bi-heart')
            } else {
                event.target.classList.add('bi-heart')
                event.target.classList.remove('bi-heart-fill')
            }
            const likeCount = document.querySelector('#like-count')
            likeCount.innerText = response.data.likeCount
        })
    })

</script>

{% comment %} 팔로우 {% endcomment %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    const followBtn = document.querySelector('#follow')
    followBtn.addEventListener('click', function(event) {
        axios({
            method: 'get',
            url: `/accounts/follow/${event.target.dataset.userId}/`
        })
        .then(response => {
            if( response.data.is_followed == true) {
                event.target.classList.remove('btn-dark')
                event.target.classList.add('btn-light')
                followBtn.innerText= '팔로잉'
            } else {
                event.target.classList.remove('btn-light')
                event.target.classList.add('btn-dark')
                followBtn.innerText='팔로우'
            }
        })
    })
</script>


{% comment %} 댓글삭제 {% endcomment %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    const replyDelete = (id) => {
        let param = {
            'replyId' : id
        }
        $.ajax({
            url : '{% url 'articles:comment_d' %}',
            type : 'POST',
            headers : {
                'X-CSRFTOKEN' : '{{ csrf_token }}'
            },
            data : JSON.stringify(param),
            success:function(data){
                if (data.result == 'ok') {
                    let replyTr = document.querySelector(`#reply${id}`)
                    let replyTr2 = document.querySelector(`#comments${id}`)
                    replyTr.remove()
                    replyTr2.remove()
                    alert('삭제 하였습니다')
                }
            },
            error: function(){
                alert('X')
            }
        })
    }
</script>
{% endblock %}

articles/templates/articles/template.html
<div class='d-flex justify-content-between'>
    <div class="d-flex mb-3">
        <div class='me-2' onclick='location.href="{% url 'accounts:mypage' comment.user.pk %}"' style='cursor: pointer;'>
            {% if comment.user.profile.image %}
            <img src="{{ comment.user.profile.image.url }}" alt="{{ comment.user.profile.image }}" style='width:2rem;height:2rem' class='rounded-circle'>
            {% else %}
            <img src="{% static 'profile/guest.png' %}" alt="guest" style='width:2rem;height:2rem' class='rounded-circle'>
            {% endif %}
        </div>
        <div class='d-flex flex-column'>
            <p class='p-0 mb-0 text-start fw-bold small' style='font-size:10px'>{{ comment.user }}</p>
            <p class='p-0 mb-0 small' style='font-size:10px'>{{ comment.create_at }}</p>
        </div>
        <div class='ms-3 mt-1'>
            <p class='fw-light'>{{ comment.content }}</p>
        </div>
    </div>
    {% if request.user == comment.user %}
    <div>
        <a href="" class='btn btn-light px-1 py-1'>수정</a>
        <a href="{% url 'articles:comment_d' comment.pk %}" class="btn btn-secondary px-1 py-1">삭제</a>
    </div>
    {% endif %}
</div>